name: Build and Release Container Image

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Policy Checks
        uses: instrumenta/conftest-action@v0.4.0
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - run: |
        git fetch --prune --unshallow --tags
      - name: Generate Semantic Release preview
        uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: master
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image with paketobuildpacks/builder
        uses: dfreilich/pack-action@v2.0.15
        with:
          args: 'build ${{ github.repository }} --builder paketobuildpacks/builder:base  --publish'

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "${{ github.repository }}:latest"
          fail-build: false
